### ISSUE TITLE
Add airspy_list_devices() api function

### ISSUE THREAD

**Issue by MartinHerren** [airspy/airspyone_host#48]
I suggest a little enhancement: add an airspy_list_devices() api function similar to the one in airspyhf.

An improvement upon the one from airspyhf would even be that given a NULL pointer in place of the serials pointer, it would just return the number of devices, thus allowing to correctly allocate the serials buffer.

**Comment by bvernoux** [comment]
Thanks for you contribution I'm waiting your feedback to you PR Airspy list devices #49 in order to merge this contribution

**Comment by MartinHerren** [comment]
Hi, what kind of feedback do you expect ?
Best regards
