### ISSUE TITLE
airspy_set_linearity_gain out of bound value problem

### ISSUE THREAD

**Issue by TLeconte** [airspy/airspyone_host#52]
In _airspy_set_linearity_gain_ (and _airspy_set_sensitivity_gain_), if an out of bound value is given (ex : 30) the **minimum** gain will bet set . Man could expect to get the **maximum** gain in this case ..

It's because the variable _value_ is an unsigned int and so the computation  : 
`value = GAIN_COUNT - 1 - value;` will not give a negative number and the following 
`if (value < 0)` is meaningless with an uint

Plus, the maximum allowed value (_GAIN_COUNT_) is not  in airspy.h and so application could not know it.

**Comment by bvernoux** [comment]
1) It is wrote in API https://github.com/airspy/airspyone_host/blob/5c86e53c484140a4a5038a24e4f40f4fb8e6240d/libairspy/src/airspy.h#L200
/* Parameter value: 0..21 */
extern ADDAPI int ADDCALL airspy_set_sensitivity_gain(struct airspy_device* device, uint8_t value);
So any developer using this API shall not exceed 21
But the best will be to explicitly move #define GAIN_COUNT (22) to this header  

2) About the if (value < 0) yes it can be removed from code ...

You can do a pull request to cleanup those minor issues thanks for your contribution
