### ISSUE TITLE
compilation

### ISSUE THREAD

**Issue by joserrecio** [airspy/airspyone_host#60]
I would like to know how can I modify the make file on the directory airspyone_host-master/build/airspy-tools to add te compilation of other functions that I have to use in the airspy_rx.c file. I mean that when you have to compile the airspy_rx.c you only have to type make in this directory but I need to compile some other files of other directories.

**Comment by bvernoux** [comment]
All is done in CMakeLists.txt for more details on how works CMake please see https://cmake.org/cmake-tutorial/
