### ISSUE TITLE
Airspy GR-Windows support

### ISSUE THREAD

**Issue by 0xCoto** [airspy/airspyone_host#71]
Not sure if this repository is related to this issue, but how could I get an Airspy Mini device to work with GNU Radio on a Windows machine? I've installed GR 3.9 with osmo and soapy but neither one recognizes the device, whereas SDR# detects it fine. Do I need to install any package with conda, or is there zero support for GR Windows?

**Comment by touil** [comment]
This is the code repository for the Airspy user mode driver and it is application agnostic. For GNU Radio support, I suggest you try their mailing list.
