### ISSUE TITLE
airspy_rx could use ppm correction option (fixed with new tool airspy_calibrate)

### ISSUE THREAD

**Issue by zanco** [airspy/airspyone_host#96]
Hi, I am running airspy_rx for satellite strf recordings. The airspy_mini is on location, wired to 1545 MHz bandpassfilter. It's observations are 3 kHz higher as the satellites center frequency.  I can not run a calibrate tool cause I have no fixed / known signal source inside the bandpassfilter range.

In SDR software I can set + 2 ppm correction which makes the frequency match for my purpose.

However airspy_rx appears to have no option to add a ppm correction. Can this be added ? Thanks.

![image](https://github.com/airspy/airspyone_host/assets/4477734/6cb20fee-bcd0-4a4a-92e3-4b24dc372901)

**Comment by bvernoux** [comment]
For that purpose I have just created a new tool airspy_calibrate to read calibration data and erase/write calibration data in ppb (see for example https://www.sitime.com/ppm-hz-calculator)
See https://github.com/airspy/airspyone_host/commit/43570b63de90dacd2c5fc6500a538617fdb406ff

**Comment by zanco** [comment]
Now running with -w 0 waiting for pass of SAR satellite. We will get there :-)

**Comment by bvernoux** [comment]
> Now running with -w 0 waiting for pass of SAR satellite. We will get there :-)

If you really need something accurate to calibrate your AirSpy (or even to use the GPSDO on 10MHz External Reference Input on Airspy R2) I heavily recommend you to buy a GPSDO like https://www.leobodnar.com "Mini Precision GPS Reference Clock" which is quite cheap for excellent performances.

**Comment by zanco** [comment]
![image](https://github.com/airspy/airspyone_host/assets/4477734/c3efc707-a8a3-47b0-bc18-24b8bf0a90e5)

It's spot on now ! Thanks a lot :-)

**Comment by bvernoux** [comment]
Thanks for all so we can close that issue
