### ISSUE TITLE
Receive callback stops being called

### ISSUE THREAD

**Issue by sivantoledo** [airspy/airspyone_host#97]
Hi, 

We have software that calls libairspy and starts streaming samples (at the default 10Ms/s rate) from an Airspy R2. On some computers, it works great.

On many others, the library stops called the receive callback at some point. The problem is not dropped samples, but that the callback is no longer being called. This happens especially on Linux. 

Is there a condition in the library that might cause it to stop calling the callback without the client requesting it to stop?

We sense that this is happening and restart our application, which reopens the Airspy and this works. The USB connection is still present.

We would appreciate any advice.

Thanks, Sivan Toledo

**Comment by touil** [comment]
Don't abuse the issue tracker for customer support. 
Check your USB connection and custom code.
